Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using B2CMultiTenant.Models;
using Microsoft.AspNetCore.Authorization;
using B2CMultiTenant.Extensions;
using Newtonsoft.Json.Linq;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.IdentityModel.Tokens;
using System.Text;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Authentication;
using System.Net.Http;
using Newtonsoft.Json;
using Microsoft.Extensions.Configuration;

namespace B2CMultiTenant.Controllers
{
    [Authorize]
    public class MembersController : Controller
    {
        public MembersController(RESTService rest)
        {
            _rest = rest;
        }
        RESTService _rest;
        // GET: Members
        public async Task<IActionResult> Index()
        {
            var tenantIdClaim = User.FindFirst("appTenantId"); // pwd reset does not return it;
            if (tenantIdClaim != null)
            {
                var http = await _rest.GetClientAsync();
                var tenantId = tenantIdClaim.Value;
                var json = await http.GetStringAsync($"{RESTService.Url}/tenant/oauth2/members");
                var members = JArray.Parse(json).Select(m => new Member
                {
                    Id = m["userId"].Value<string>(),
                    Roles = (m["roles"].ToList().Select(t => t.Value<string>()).Aggregate((i, r) => $"{i}, {r}")),
                    DisplayName = m["name"].Value<string>()
                }).ToList();
                return View(members);
            }
            return View();
        }

        [Authorize(Roles ="admin")]
        public IActionResult Invite()
        {
            return View(new Invitee());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="admin")]
        public async Task<IActionResult> Invite([Bind("Email,IsAdmin")] Invitee invitee)
        {
            if (ModelState.IsValid)
            {
                var http = await _rest.GetClientAsync();
                var role = invitee.IsAdmin ? "admin" : "member";
                var replyUrl = $"{Request.Scheme}://{Request.Host}/members/redeem";
                var invitation = new { inviteEmail = invitee.Email, postRedeemUrl = replyUrl, additionalClaims = new Dictionary<string, string>() { { "role", role } } };
                var resp = await http.PostAsync($"{RESTService.Url}/tenant/oauth2/invite",
                   new StringContent(
                        JsonConvert.SerializeObject(invitation),
                        System.Text.Encoding.UTF8,
                        "application/json"));
                if (resp.IsSuccessStatusCode)
                    invitee.InvitationUrl = await resp.Content.ReadAsStringAsync();
                return View(invitee);
                //return RedirectToAction(nameof(Invite));
            }
            return View(new Invitee());
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Redeem(string id_token)
        {
            // will not validate the token since we will send the user back for signin anyway
            // Occassionally getting B2C error that user does not exists - presumably timing error between session state, which things user exists and b2C data where user not yet created.
            await Task.Delay(10000); // wait 10s
            var tokenHandler = new JwtSecurityTokenHandler();
            var token = tokenHandler.ReadJwtToken(id_token);
            var tenant = token.Claims.FirstOrDefault(c => c.Type == "appTenantName").Value;
            return RedirectToAction("Index", "Home", new { tenant });
        }

        /*

        // GET: Members/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .FirstOrDefaultAsync(m => m.Id == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // GET: Members/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Role,DisplayName")] Member member)
        {
            if (ModelState.IsValid)
            {
                _context.Add(member);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Role,DisplayName")] Member member)
        {
            if (id != member.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberExists(member.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .FirstOrDefaultAsync(m => m.Id == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var member = await _context.Member.FindAsync(id);
            _context.Member.Remove(member);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MemberExists(string id)
        {
            return _context.Member.Any(e => e.Id == id);
        }
        */

    }
}

Controllers/TenantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using B2CMultiTenant.Extensions;
using B2CMultiTenant.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace B2CMultiTenant.Controllers
{
    [Authorize(Roles = "admin")]
    public class TenantController : Controller
    {
        public TenantController(RESTService rest)
        {
            _rest = rest;
        }
        RESTService _rest;
        public async Task<ActionResult> Edit()
        {
            var http = await _rest.GetClientAsync();
            var json = await http.GetStringAsync($"{RESTService.Url}/tenant/oauth2");
            var tenant = JObject.Parse(json);
            var details = new TenantDetails
            {
                Name = tenant["name"].Value<string>(),
                LongName = tenant["description"].Value<string>(),
                RequireMFA = tenant["requireMFA"].Value<bool>(),
            };
            var idp = tenant["identityProvider"].Value<string>();
            if (!String.IsNullOrEmpty(idp) && idp.Equals("commonaad"))
            {
                details.OwnerIssuer = tenant["directoryId"].Value<string>();
                details.AllowNoInviteFromSameIssuer = tenant["allowSameIssuerMembers"].Value<bool>();
            }
            return View(details) ;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind("Name,LongName,RequireMFA")] TenantDetails tenant)
        {
            try
            {
                var http = await _rest.GetClientAsync();
                var details = new
                {
                    name = tenant.Name,
                    description = tenant.LongName,
                    requireMFA = tenant.RequireMFA
                };
                var json = await http.PutAsync(
                    $"{RESTService.Url}/tenant/oauth2/",
                    new StringContent(JsonConvert.SerializeObject(details), Encoding.UTF8, "application/json"));
                return RedirectToAction(nameof(Edit));
            }
            catch(Exception ex)
            {
                throw;
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - B2CMultiTenant</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <script type="text/javascript">
        function copyToCB(id) {
              alert("Coping the text");
              var copyText = document.getElementById(id);
              copyText.select();
              copyText.setSelectionRange(0, 99999); /*For mobile devices*/
              document.execCommand("copy");
        }
        function selectTenant() {
            var selectBox = document.getElementById("tenants");
            var selectedValue = selectBox.options[selectBox.selectedIndex].value;
            //alert('/home/index?tenant='+ selectedValue);
            window.location.href = '/home/index?tenant=' + selectedValue;
        }
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">B2CMultiTenant</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Index">Members</a>
                            </li>
                            @if (User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tenant" asp-action="Edit">Tenant</a>
                                </li>
                            }
                        }
                    </ul>
                        <partial name="_LoginPartial" />
                    </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - B2CMultiTenant - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*<div class="text-center">
        <p> Sorry, fixing some bugs. Should be back in a few days (+-2/20/2020)</p>
    </div>*@

    @RenderSection("Scripts", required: false)
</body>
</html>